name: math_blitz
description: "Mini Math Game"
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/math_blitz_logo_final.png"
flutter:
  uses-material-design: true
